apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  restartPolicy: OnFailure
  containers:
  - name: alpine
    image: alpine
    command: ['cat']
    tty: true
    securityContext:
      privileged: true

    volumeMounts:
    - name: host-root
      mountPath: /home/root
      readOnly: false
  volumes:
  - name: host-root
    hostPath:
      path: /