apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  restartPolicy: OnFailure
  containers:
  - name: busybox
    image: busybox
    command: ['cat']
    tty: true
    volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker
     
  volumes:
  - name: docker-config
    projected:
      sources:
      - secret:
          name: dockercred
          items:
            - key: .dockerconfigjson
              path: config.json 
  - name: config-map
    configMap:
      name: proper             
 