apiVersion: v1
kind: Pod
metadata:
  name: build-image
spec:
  restartPolicy: OnFailure
  containers:
  - name: containerd
    image: gprasath/crictl:ci
    command: ['cat']
    tty: true
    securityContext:
      privileged: true

    volumeMounts:
    - name: docker-socket
      mountPath: /run/containerd/containerd.sock
      readOnly: false
  volumes:
  - name: docker-socket
    hostPath:
      path: /run/containerd/containerd.sock

