apiVersion: v1
kind: Pod
metadata:
  name: kanikocred
spec:
  restartPolicy: OnFailure
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ['/busybox/cat']
    tty: true
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker
  volumes:
  - name: jenkins-docker-cfg
    secret:
      secretName: dockercred
    

    
    